### PR TITLE
add depreciation page and contributor components

### PR DESCRIPTION
**Pull request by lucasmarohn**

### CODE REVIEW

**Review by kinabalu — COMMENTED** [review]
Looks good to me @pr3d4t0r can you review? we can add other contributors below the top line folks

**Comment by kinabalu** [comment]
Running this locally, I see that the entire frame of the site is still there. I think we should ensure that all roads lead to a simple notice of deprecation. No ability to browse around any longer.

**Comment by kinabalu** [comment]
Oh and the word is probably better as "Deprecated" or possibly other

**Comment by lucasmarohn** [comment]
Updated @kinabalu 
- Removed navigation and routing
- Changed word

**Comment by pr3d4t0r** [comment]
About CIME:

**[CIME Software Ltd](https://cime.net)** is a consultancy that offers strategic technology planning in the areas of machine learning, exploratory analysis of unstructured data, and high performance system design to private and government entities in Europe, Asia, and Northamerica.  6 successful exits in the last 10 years are the result of 15+ years of applied experience in these technological areas.  VirusTrack was a successful application of CIME's expertise in assembling a world-class team and delivering a production-ready, robust working system that would've taken other firms months to develop and deploy.  Reach out to our principals **[via LinkedIn](https://www.linkedin.com/in/ciurana/)**.

**Comment by pr3d4t0r** [comment]
And CIME logo - thank you!
CIME_trans

**Pull request merged**
